### ISSUE TITLE
Technical specifications in the swagger.yaml

### ISSUE THREAD

**Issue by katr1234** [htl-perg-2019-20-5ahif/contact-list-exercise-katr1234#1]
Dear Mr. Stropek,

i think i have implemented all the technical specifications defined in the swagger.yaml file.

Kind regards
Kathrin

**Comment by rstropek** [comment]
Avoid checking in unnecessary files (e.g. *bin* folder).

**Comment by rstropek** [comment]
Added minor feedback (comments). In general, specs have been implemented. The extra point is yours.

Greetings,
Rainer Stropek.
